version: '3.6'

networks: 
  traefik-net:
    name: system_traefik-net
    external: true

volumes:
  traefik-data:

services:
  app:
    image: nextcloud:latest
    ports:
      - 8080:80
    networks:
      - traefik-net
    volumes:
      - traefik-data:/var/www/html
      - /var/data/cloud:/var/www/html/data
    environment:
      PUID: 33		#www-data	
      PGID: 33		#www-data
      SQLITE_DATABASE: cloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: hypriot
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "false"        # todo: cflat-srv/cloud is not working -> use: sflat-srv.local:8080
        traefik.port: "80"
        traefik.backend: "nextcloud"
        traefik.default.protocol: "http"
        traefik.frontend.rule: "PathPrefixStrip:/cloud"
        traefik.docker.network: "system_traefik-net"
