version: '3.6'

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer_agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  app:
    image: portainer/portainer
    command: -H tcp://tasks.portainer_agent:9001 --tlsskipverify --no-auth
    expose:
      - "9000"
    volumes:
      - data:/data
    networks:
      - agent_network
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"  
        traefik.backend: "heimdall"
        traefik.frontend.rule: "PathPrefixStrip:/portainer"
        traefik.port: "9000"
        traefik.docker.network: "traefik_proxy-net"

volumes:
  data:

networks:
  agent_network:
    driver: overlay
    attachable: true 
  proxy-net:
    name: traefik_proxy-net
    external: true
