#cloud-config
#

# The current version of cloud-init in the Hypriot rpi-64 is 0.7.9
# When dealing with cloud-init, it is SUPER important to know the version
# I have wasted many hours creating servers to find out the module I was trying to use wasn't in the cloud-init version I had
# Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

hostname: cflat-srv
manage_etc_hosts: true

resize_rootfs: true
growpart:
    mode: auto
    devices: ["/"]
    ignore_growroot_disabled: false

users: 
  - name: admin
    gecos: "Administrator"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - ntp
  - acl

locale: "en_US.UTF-8"
timezone: "Europe/Zurich"

write_files:
    - path: "/etc/docker/daemon.json"
      owner: "root:root"
      content: |
        {
         "labels": [ "os=linux", "arch=arm64" ],
         "experimental": true
        }

# These commands will be ran on every boot
bootcmd:
  # Build Persisten-Disc: USB-disk/vol:data -> /var/data
  - sudo mkdir -p /var/data
  - sudo mount /dev/disk/by-label/data /var/data
  
  - sudo rm -rf $PWD/cflat-server && curl -L https://github.com/cgHome/cflat-server/tarball/master | tar xz -C $PWD --strip=1 --one-top-level=cflat-server

  - sudo chown -R www-data:www-data /var/data/
# These commands will be ran once on first boot only
runcmd:
  - [ systemctl, restart, avahi-daemon ]
  - [ systemctl, restart, docker ]
  - [ docker, swarm, init ]

  # Workaround 
  - sudo apt-get update && sudo apt-get install acl

  - curl -L https://github.com/cgHome/cflat-server/tarball/master | tar xz -C /home/admin --strip=1 --one-top-level=cflat-server
  
  - docker stack deploy -c /home/admin/cflat-server/docker/mbase-stack.yml mbase
  - docker stack deploy -c /home/admin/cflat-server/docker/heimdall/docker-compose.yml heimdall

  # - docker stack deploy -c /home/admin/cflat-server/docker/portainer/docker-compose.yml portainer
  #- sudo mkdir -p /var/data/portainer
  #- docker network create --driver overlay --attachable portainer_agent-net
  #- docker service create --detach=false --name portainer_agent --network portainer_agent-net -e  AGENT_CLUSTER_ADDR=tasks.portainer_agent --mode global --constraint 'node.platform.os == linux' --mount type=bind,src=//var/run/docker.sock,dst=/var/run/docker.sock portainer/agent
  #- docker service create --detach=false --name portainer_app --network portainer_agent-net --publish 9000:9000 --replicas=1 --constraint 'node.role == manager' --mount type=bind,src=/var/data/portainer,dst=/data portainer/portainer -H 'tcp://tasks.portainer_agent:9001' --tlsskipverify --no-auth

 
  # registry
  - [ sudo, mkdir, -p, /var/data/registry ]
  - [
      docker, service, create, 
       "--detach=false",
       "--name registry",
       "--publish 5000:5000",
       "--replicas 1",
       "--constraint  node.role==manager",
       "--mount  type=bind,src=/var/data/registry,dst=/var/lib/registry,ro",
       "--no-resolve-image",
       "cblomart/rpi-registry"
    ]
   
power_state:
  message: "*** Reboot after runcmd is finished ***"
#  mode: reboot
