#cloud-config
#

# The current version of cloud-init in the Hypriot rpi-64 is 0.7.9
# When dealing with cloud-init, it is SUPER important to know the version
# I have wasted many hours creating servers to find out the module I was trying to use wasn't in the cloud-init version I had
# Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

hostname: cflat-srv
manage_etc_hosts: true

resize_rootfs: true
growpart:
    mode: auto
    devices: ["/"]
    ignore_growroot_disabled: false

users: 
  - name: admin
    gecos: "Administrator"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video
    plain_text_passwd: hypriot
    lock_passwd: false
    ssh_pwauth: true
    chpasswd: { expire: false }

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - ntp
  - acl

locale: "en_US.UTF-8"
timezone: "Europe/Zurich"

write_files:
    - path: "/etc/docker/daemon.json"
      owner: "root:root"
      content: |
        {
         "labels": [ "os=linux", "arch=arm64" ],
         "experimental": true
        }

# These commands will be ran on every boot
bootcmd:
  # Build Persisten-Disc: USB-disk/vol:data -> /var/data
  - sudo mkdir -p /var/data
  - sudo mount /dev/disk/by-label/data /var/data
  - sudo chown -R www-data:www-data /var/data/

# These commands will be ran once on first boot only
runcmd:
  # Workaround 
  - sudo apt-get update && sudo apt-get install acl

  - [ systemctl, restart, avahi-daemon ]
  - [ systemctl, restart, docker ]

  - docker swarm init
  - docker stack deploy -c <(curl -L https://raw.githubusercontent.com/cgHome/cflat-server/master/portainer/docker-compose.yml) portainer
 
  # registry
  - [ sudo, mkdir, -p, /var/data/registry ]
  - [
      docker, service, create, 
       "--detach=false",
       "--name registry",
       "--publish 5000:5000",
       "--replicas 1",
       "--constraint  node.role==manager",
       "--mount  type=bind,src=/var/data/registry,dst=/var/lib/registry,ro",
       "--no-resolve-image",
       "cblomart/rpi-registry"
    ]
   
power_state:
  message: "*** Reboot after runcmd is finished ***"
#  mode: reboot
