version: "3.6"
services:
  registry:
    image: cblomart/rpi-registry
    ports:
      - 5000:5000
    environment:
      - $REGISTRY_PROXY_REMOTEURL="https://registry-1.docker.io"
    volumes:
      - /var/data/registry:/var/lib/registry
    deploy:
      placement:
        constraints:
         - 'node.role == manager'
