version: '3.6'

networks:
  agent-net:
    driver: overlay
    attachable: true
# proxy-net:
#   name: traefik_proxy-net
#   external: true

volumes:
  app-data:

services:
  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  app:
    image: portainer/portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify --no-auth --templates https://raw.githubusercontent.com/cgHome/cflat-server/master/proxy/templates.json
    volumes:
      - app-data:/data
    ports:
      - 9000:9000
    networks:
      - agent-net
      #- proxy-net
    depends_on:
      - agent
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "false" 
        traefik.port: "9000"
        traefik.backend: "docker-ui"
        traefik.frontend.rule: "PathPrefixStrip:/docker-ui"
        traefik.docker.network: "traefik_proxy-net"
