version: '3.6'

services:
  proxy:
    image: traefik
    command:
      - "--api"
      #- "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=localhost"
      - "--docker.watch"
      - "--logLevel=INFO"
    networks:
      - backend-net
    ports:
      - 80:80
      - 443:443
      #- 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      #- /dev/null:/acme.json
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "false"
        traefik.backend: "traefik"
        traefik.port: "9000"
        #traefik.frontend.rule=Host:traefik.${HOSTNAME}.local"  
        traefik.frontend.rule: "PathPrefixStrip: /traefik"
        traefik.docker.network: "proxy_backend-net"

networks:
  backend-net:
    name: proxy_backend-net
    driver: overlay