version: '3.6'

networks:
  proxy-net:
    name: traefik_proxy-net
    driver: overlay

services:
  app:
    image: traefik:latest
    command:
      - "--api"
      #- "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entrypoints=Name:http Address::80"
      - "--entrypoints=Name:https Address::443 TLS"
      - "--defaultentrypoints=http,https"
      - "--docker"
      - "--docker.swarmMode"
      - "--docker.domain=localhost"
      - "--docker.watch"
      - "--logLevel=INFO"
    networks:
      - proxy-net
    ports:
      - 80:80
      - 443:443
      - 8888:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- /dev/null:/traefik.toml
      #- /dev/null:/acme.json
    deploy:
      mode: global
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "false"       # Not working a the moment issue: traefik/3282
        traefik.port: "8080"
        traefik.backend: "proxy"
        traefik.frontend.rule: "PathPrefixStrip:/proxy"
        traefik.docker.network: "traefik_proxy-net"
