version: '3.6'

services:
  app:
    image: nextcloud:latest
    volumes:
      - type: volume
        source: config
        target: /var/www/html
      - type: bind
        source: /var/data/cloud 
        target: /var/www/html/data
    networks:
      - proxy-net
    environment:
      PUID: 33		#www-data	
      PGID: 33		#www-data
      SQLITE_DATABASE: cloud
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: hypriot
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        traefik.enable: "true"        # todo: cflat-srv/cloud is not working -> use: sflat-srv:88  
        traefik.backend: "nextcloud"
        traefik.frontend.rule: "Host:${HOSTNAME}; PathPrefixStrip:/cloud"
        traefik.port: "80"
        traefik.docker.network: "traefik_proxy-net"

volumes:
  config:

networks: 
  proxy-net:
    name: traefik_proxy-net
    external: true
